package com.unindra.service;

import java.time.LocalDate;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.unindra.entity.Student;
import com.unindra.model.RegisterRequest;
import com.unindra.model.RegisterUserRequest;
import com.unindra.repository.StudentRepository;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Service
public class StudentService {

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private ValidationService validationService;

    @Autowired
    private PasswordService passwordService;
    
    public String add(RegisterRequest request) {
        
        String errorMessage = validationService.validate(request);

        if (errorMessage != null) {
            return errorMessage;
        }

        if (isUsernameExist(request.getUsername())) {
            return "Username sudah digunakan";
        }

        if (!passwordService.isPasswordEquals(request.getPassword(), request.getConfirmPassword())) {
            return "Password tidak sama";
        }

        String hashedPassword = passwordService.generateHashPw(request.getPassword());
        String birthPlace = String.join(", ",request.getDistrict(), request.getCity(), request.getProvience());

        Integer year = Integer.parseInt(request.getYearBirth());
        Integer month = request.getMonthBirth() + 1;
        Integer date = Integer.parseInt(request.getDateBirth());

        LocalDate localDate = LocalDate.of(year, month, date);

        Student student = new Student();
        student.setName(request.getFullName());
        student.setUsername(request.getUsername());
        student.setPassword(hashedPassword);
        student.setEmail(request.getEmail());
        student.setPhoneNumber(request.getPhoneNumber());
        student.setBirthDate(localDate);
        student.setBirthPlace(birthPlace);

        studentRepository.save(student);

        return null;
    }

    public String add(RegisterUserRequest request) {
        
        String errorMessage = validationService.validate(request);

        if (errorMessage != null) {
            return errorMessage;
        }

        if (isUsernameExist(request.getUsername())) {
            return "Username sudah digunakan";
        }

        // password generated by birthdate
        String password = String.join("", request.getDateBirth(), String.valueOf(request.getMonthBirth()), request.getYearBirth());

        String hashedPassword = passwordService.generateHashPw(password);
        String birthPlace = String.join(", ",request.getDistrict(), request.getCity(), request.getProvience());

        Integer year = Integer.parseInt(request.getYearBirth());
        Integer month = request.getMonthBirth() + 1;
        Integer date = Integer.parseInt(request.getDateBirth());

        LocalDate localDate = LocalDate.of(year, month, date);

        Student student = new Student();
        student.setName(request.getFullName());
        student.setUsername(request.getUsername());
        student.setPassword(hashedPassword);
        student.setEmail(request.getEmail());
        student.setPhoneNumber(request.getPhoneNumber());
        student.setBirthDate(localDate);
        student.setBirthPlace(birthPlace);

        studentRepository.save(student);

        return null;
    }

    public String edit(RegisterUserRequest request) {
        
        String errorMessage = validationService.validate(request);

        if (errorMessage != null) {
            return errorMessage;
        }

        Optional<Student> userWithUsername = studentRepository.findByUsername(request.getUsername());

        if (userWithUsername.isPresent() && !userWithUsername.get().getId().equals(request.getId())) {
            return "Username sudah dipakai oleh pengguna lain";
        }
    
        // Ambil student berdasarkan ID (bukan username!)
        Student student = studentRepository.findById(request.getId())
                .orElseThrow(() -> new IllegalArgumentException("Data tidak ditemukan"));
    
        student.setName(request.getFullName());
        student.setUsername(request.getUsername());
        student.setEmail(request.getEmail());
        student.setPhoneNumber(request.getPhoneNumber());

        Integer year = Integer.parseInt(request.getYearBirth());
        Integer month = request.getMonthBirth() + 1;
        Integer date = Integer.parseInt(request.getDateBirth());

        LocalDate localDate = LocalDate.of(year, month, date);
        String birthPlace = String.join(", ",request.getDistrict(), request.getCity(), request.getProvience());

        student.setBirthDate(localDate);
        student.setBirthPlace(birthPlace);

        studentRepository.save(student);

        return null;
    }

    public boolean isUsernameExist(String username) {
        return studentRepository.existsByUsername(username);
    }
    
    public List<Student> getAll() {
        return studentRepository.findAll();
    }

    public Optional<Student> findStudentByUsername(String username) {
        return studentRepository.findByUsername(username);
    }

    public void deleteById(String id) {
        studentRepository.deleteById(id);
    }

    public List<Student> searchStudents(String keyword) {
        if (keyword == null || keyword.trim().isEmpty()) {
            return studentRepository.findAll(); // kembalikan semua kalau kosong
        }
        return studentRepository.searchAllFields(keyword.trim());
    }
}
