/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.view;

import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 *
 * @author rizmakiana
 */
@Component
public class RegisterStudentView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     * 
     * @param role
     */
    public RegisterStudentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameForm = new javax.swing.JTextField();
        usernameForm = new javax.swing.JTextField();
        phoneNumberForm = new javax.swing.JTextField();
        emailForm = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        dateForm = new javax.swing.JComboBox<>();
        yearForm = new javax.swing.JComboBox<>();
        monthForm = new javax.swing.JComboBox<>();
        dateForm1 = new javax.swing.JComboBox<>();
        dateForm2 = new javax.swing.JComboBox<>();
        dateForm3 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullnameForm.setBackground(new java.awt.Color(216, 216, 216));
        fullnameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(fullnameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 300, 30));

        usernameForm.setBackground(new java.awt.Color(216, 216, 216));
        usernameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 130, 30));

        phoneNumberForm.setBackground(new java.awt.Color(216, 216, 216));
        phoneNumberForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(phoneNumberForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 220, 30));

        emailForm.setBackground(new java.awt.Color(216, 216, 216));
        emailForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(emailForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 210, 30));

        password.setBackground(new java.awt.Color(216, 216, 216));
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 210, 30));

        confirmPassword.setBackground(new java.awt.Color(216, 216, 216));
        confirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 220, 30));

        dateForm.setBackground(new java.awt.Color(216, 216, 216));
        dateForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 460, 20));

        yearForm.setBackground(new java.awt.Color(216, 216, 216));
        yearForm.setModel(new javax.swing.DefaultComboBoxModel<>(getYears()));
        yearForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(yearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 130, 30));

        monthForm.setBackground(new java.awt.Color(216, 216, 216));
        monthForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(monthForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 130, 30));

        dateForm1.setBackground(new java.awt.Color(216, 216, 216));
        dateForm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateForm1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 210, 30));

        dateForm2.setBackground(new java.awt.Color(216, 216, 216));
        dateForm2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateForm2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 210, 30));

        dateForm3.setBackground(new java.awt.Color(216, 216, 216));
        dateForm3.setModel(new javax.swing.DefaultComboBoxModel<>(getDates()));
        dateForm3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 140, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Register View.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 40, 40));

        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 543, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_registerButtonMouseClicked

    public String[] getYears() {

        int currentYear = Year.now().getValue();
        int startYear = currentYear - 17; // 50 tahun yang lalu
        int endYear = currentYear - 6;   // 18 tahun yang lalu

        List<String> years = new ArrayList<>();
        for (int year = startYear; year <= endYear; year++) {
            years.add(String.valueOf(year));
        }

        return years.toArray(String[]::new);
    }
    
    public String[] getDates(){
        List<String> dates = new ArrayList<>();
        
        for (int i = 1; i <= 31; i++) {
            dates.add(String.valueOf(i));
        }
        
        return dates.toArray(new String[0]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JComboBox<String> dateForm;
    private javax.swing.JComboBox<String> dateForm1;
    private javax.swing.JComboBox<String> dateForm2;
    private javax.swing.JComboBox<String> dateForm3;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField fullnameForm;
    private javax.swing.JComboBox<String> monthForm;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNumberForm;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameForm;
    private javax.swing.JComboBox<String> yearForm;
    // End of variables declaration//GEN-END:variables
}
