/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.view;

import com.unindra.model.RegisterRequest;
import com.unindra.service.RegionService;
import com.unindra.service.StaffService;

import java.time.Year;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author rizmakiana
 */
@Component
@Slf4j
public class RegisterStaffView extends javax.swing.JFrame {

    private final RegionService regionService;

    private final StaffService staffService;

    /**
     * Creates new form RegisterView
     * 
     * @param role
     */
    @Autowired
    public RegisterStaffView(RegionService regionService, StaffService staffService) {
        this.regionService = regionService;
        this.staffService = staffService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameForm = new javax.swing.JTextField();
        usernameForm = new javax.swing.JTextField();
        phoneNumberForm = new javax.swing.JTextField();
        emailForm = new javax.swing.JTextField();
        confirmPasswordForm = new javax.swing.JPasswordField();
        passwordForm = new javax.swing.JPasswordField();
        dateForm = new javax.swing.JComboBox<>();
        provinceForm = new javax.swing.JComboBox<>();
        monthForm = new javax.swing.JComboBox<>();
        yearForm = new javax.swing.JComboBox<>();
        cityForm = new javax.swing.JComboBox<>();
        districtForm = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullnameForm.setBackground(new java.awt.Color(216, 216, 216));
        fullnameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(fullnameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 300, 30));

        usernameForm.setBackground(new java.awt.Color(216, 216, 216));
        usernameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 130, 30));

        phoneNumberForm.setBackground(new java.awt.Color(216, 216, 216));
        phoneNumberForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(phoneNumberForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 220, 30));

        emailForm.setBackground(new java.awt.Color(216, 216, 216));
        emailForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(emailForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 210, 30));

        confirmPasswordForm.setBackground(new java.awt.Color(216, 216, 216));
        confirmPasswordForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(confirmPasswordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 210, 30));

        passwordForm.setBackground(new java.awt.Color(216, 216, 216));
        passwordForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(passwordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 220, 30));

        dateForm.setBackground(new java.awt.Color(216, 216, 216));
        dateForm.setModel(new javax.swing.DefaultComboBoxModel<>(getDates()));
        dateForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 140, 30));

        provinceForm.setBackground(new java.awt.Color(216, 216, 216));
        provinceForm.setModel(new javax.swing.DefaultComboBoxModel<>(getProvinces()));
        provinceForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        provinceForm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                provinceFormItemStateChanged(evt);
            }
        });
        getContentPane().add(provinceForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 460, 20));

        monthForm.setBackground(new java.awt.Color(216, 216, 216));
        monthForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(monthForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 130, 30));

        yearForm.setBackground(new java.awt.Color(216, 216, 216));
        yearForm.setModel(new javax.swing.DefaultComboBoxModel<>(getYears()));
        yearForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(yearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 130, 30));

        cityForm.setBackground(new java.awt.Color(216, 216, 216));
        cityForm.setModel(new javax.swing.DefaultComboBoxModel<>(getRegencies()));
        cityForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cityForm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityFormItemStateChanged(evt);
            }
        });
        getContentPane().add(cityForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 210, 30));

        districtForm.setBackground(new java.awt.Color(216, 216, 216));
        districtForm.setModel(new javax.swing.DefaultComboBoxModel<>(getDistricts()));
        districtForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(districtForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 210, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Register View.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 40, 40));

        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 543, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }// GEN-LAST:event_backButtonMouseClicked

    private void provinceFormItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_provinceFormItemStateChanged
        // TODO add your handling code here:
        getRegencies();
        cityForm.setModel(new javax.swing.DefaultComboBoxModel<>(getRegencies()));
        getDistricts();
        districtForm.setModel(new javax.swing.DefaultComboBoxModel<>(getDistricts()));
    }// GEN-LAST:event_provinceFormItemStateChanged

    private void cityFormItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cityFormItemStateChanged
        // TODO add your handling code here:

        getDistricts();
        districtForm.setModel(new javax.swing.DefaultComboBoxModel<>(getDistricts()));

    }// GEN-LAST:event_cityFormItemStateChanged

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:

        String name = fullnameForm.getText();
        String username = usernameForm.getText();
        String password = passwordForm.getText();
        String confirmPassword = confirmPasswordForm.getText();
        String date = dateForm.getSelectedItem().toString();
        Integer month = monthForm.getSelectedIndex();
        String year = yearForm.getSelectedItem().toString();
        String email = emailForm.getText();
        String phoneNumber = phoneNumberForm.getText();
        String province = provinceForm.getSelectedItem().toString();
        String city = cityForm.getSelectedItem().toString();
        String district = districtForm.getSelectedItem().toString();

        RegisterRequest request = new RegisterRequest(name, username, password, confirmPassword, date, month, year, email, phoneNumber, province, city, district);

        try {
            String result = staffService.add(request);

            if (result != null) {
                JOptionPane.showMessageDialog(this, result, "Validasi Gagal", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_registerButtonMouseClicked

    public String[] getYears() {

        int currentYear = Year.now().getValue();
        int startYear = currentYear - 17; // 50 tahun yang lalu
        int endYear = currentYear - 6; // 18 tahun yang lalu

        List<String> years = new ArrayList<>();
        for (int year = startYear; year <= endYear; year++) {
            years.add(String.valueOf(year));
        }

        return years.toArray(String[]::new);
    }

    public String[] getDates() {
        List<String> dates = new ArrayList<>();

        for (int i = 1; i <= 31; i++) {
            dates.add(String.valueOf(i));
        }

        return dates.toArray(new String[0]);
    }

    public String[] getProvinces() {
        return regionService.getAllProvinces();
    }

    public String[] getRegencies() {
        Object selectedProvince = provinceForm.getSelectedItem();

        if (selectedProvince == null) {
            return new String[] {};
        }

        String provinceName = selectedProvince.toString();
        log.info("provinceName = {}", provinceName);

        return regionService.getRegenciesByName(provinceName);
    }

    public String[] getDistricts() {
        Object selectedRegency = cityForm.getSelectedItem();

        if (selectedRegency == null) {
            return new String[] {};
        }

        String regencyName = selectedRegency.toString();
        log.info("VIEW : {}", regencyName);
        return regionService.getDistrictsByName(regencyName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cityForm;
    private javax.swing.JPasswordField confirmPasswordForm;
    private javax.swing.JComboBox<String> dateForm;
    private javax.swing.JComboBox<String> districtForm;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField fullnameForm;
    private javax.swing.JComboBox<String> monthForm;
    private javax.swing.JPasswordField passwordForm;
    private javax.swing.JTextField phoneNumberForm;
    private javax.swing.JComboBox<String> provinceForm;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameForm;
    private javax.swing.JComboBox<String> yearForm;
    // End of variables declaration//GEN-END:variables
}
