/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.view;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author rizmakiana
 */
@Component
public class SelectRoleView extends javax.swing.JFrame {
    
    private final TeacherLoginView teacherLoginView;
    
    private final StudentLoginView studentLoginView;
    
    private final StaffLoginView staffLoginView;

    /**
     * Creates new form SelectRoleView
     */
    @Autowired
    public SelectRoleView(TeacherLoginView teacherLoginView, StudentLoginView studentLoginView, StaffLoginView staffLoginView) {
        this.teacherLoginView = teacherLoginView;
        this.studentLoginView = studentLoginView;
        this.staffLoginView = staffLoginView;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        studentButton = new javax.swing.JButton();
        teacherButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Select Role.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        studentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentButtonMouseClicked(evt);
            }
        });
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 240, 360));

        teacherButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherButtonMouseClicked(evt);
            }
        });
        getContentPane().add(teacherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 240, 360));

        staffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffButtonMouseClicked(evt);
            }
        });
        getContentPane().add(staffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 240, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentButtonMouseClicked
        // TODO add your handling code here:
        openStudentLogin();
    }//GEN-LAST:event_studentButtonMouseClicked

    private void teacherButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherButtonMouseClicked
        // TODO add your handling code here:
        openTeacherLogin();
    }//GEN-LAST:event_teacherButtonMouseClicked

    private void staffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseClicked
        // TODO add your handling code here:
        openStaffLogin();
    }//GEN-LAST:event_staffButtonMouseClicked

    private void openTeacherLogin(){
        teacherLoginView.setVisible(true);
    }
    
    private void openStudentLogin(){
        studentLoginView.setVisible(true);
    }
    
    private void openStaffLogin(){
        staffLoginView.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton teacherButton;
    // End of variables declaration//GEN-END:variables
}
