/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.view.teacher;

import com.unindra.service.ProvinceService;
import org.springframework.stereotype.Component;

/**
 *
 * @author rizmakiana
 */
@Component
public class RegisterTeacherView extends javax.swing.JFrame {
    
    private ProvinceService provinceService;

    /**
     * Creates new form RegisterView
     * 
     * @param role
     */
    public RegisterTeacherView(ProvinceService provinceService) {
        this.provinceService = provinceService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameForm = new javax.swing.JTextField();
        genderForm = new javax.swing.JComboBox<>();
        usernameForm = new javax.swing.JTextField();
        phoneNumberForm = new javax.swing.JTextField();
        emailForm = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        dateForm = new javax.swing.JComboBox<>();
        monthForm = new javax.swing.JComboBox<>();
        yearForm = new javax.swing.JComboBox<>();
        provinceForm = new javax.swing.JComboBox<>();
        cityForm = new javax.swing.JComboBox<>();
        districtForm = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullnameForm.setBackground(new java.awt.Color(216, 216, 216));
        fullnameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(fullnameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 200, 315, 25));

        genderForm.setBackground(new java.awt.Color(216, 216, 216));
        genderForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        genderForm.setBorder(null);
        getContentPane().add(genderForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 125, 25));

        usernameForm.setBackground(new java.awt.Color(216, 216, 216));
        usernameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 255, 140, 25));

        phoneNumberForm.setBackground(new java.awt.Color(216, 216, 216));
        phoneNumberForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(phoneNumberForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 365, 220, 25));

        emailForm.setBackground(new java.awt.Color(216, 216, 216));
        emailForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(emailForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 365, 220, 25));

        password.setBackground(new java.awt.Color(216, 216, 216));
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 255, 140, 25));

        confirmPassword.setBackground(new java.awt.Color(216, 216, 216));
        confirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 255, 140, 25));

        dateForm.setBackground(new java.awt.Color(216, 216, 216));
        dateForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(dateForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 310, 140, 25));

        monthForm.setBackground(new java.awt.Color(216, 216, 216));
        monthForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(monthForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 310, 140, 25));

        yearForm.setBackground(new java.awt.Color(216, 216, 216));
        yearForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(yearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 310, 140, 25));

        provinceForm.setBackground(new java.awt.Color(216, 216, 216));
        provinceForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(provinceForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 420, 140, 25));

        cityForm.setBackground(new java.awt.Color(216, 216, 216));
        cityForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(cityForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 420, 140, 25));

        districtForm.setBackground(new java.awt.Color(216, 216, 216));
        districtForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(districtForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 420, 140, 25));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/Register View Teacher.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 40, 40));

        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 543, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        this.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_registerButtonMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cityForm;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JComboBox<String> dateForm;
    private javax.swing.JComboBox<String> districtForm;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField fullnameForm;
    private javax.swing.JComboBox<String> genderForm;
    private javax.swing.JComboBox<String> monthForm;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNumberForm;
    private javax.swing.JComboBox<String> provinceForm;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameForm;
    private javax.swing.JComboBox<String> yearForm;
    // End of variables declaration//GEN-END:variables
}
