/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.view.staff;

import com.unindra.view.staff.RegisterStaffView;
import javax.swing.JOptionPane;

import org.springframework.stereotype.Component;

import com.unindra.model.LoginRequest;
import com.unindra.service.AuthService;

/**
 *
 * @author rizmakiana
 */
@Component
public class StaffLoginView extends javax.swing.JFrame {

    private final RegisterStaffView registerStaffView;

    private final AuthService authService;
    
//    private final StaffDashboardView staffDashboardView;
    private final Dashboard dashboard;
    /**
     * Creates new form LoginStudentView
     */
    public StaffLoginView(RegisterStaffView registerStaffView, AuthService authService, Dashboard dashboard) {
        this.registerStaffView = registerStaffView;
        this.authService = authService;
        this.dashboard = dashboard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameForm = new javax.swing.JTextField();
        passwordForm = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 285, 250, 30));

        passwordForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(passwordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 250, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Login View Admin.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1192, 10, 70, 30));

        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 270, 40));

        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        registerStaffView.setVisible(true);
    }//GEN-LAST:event_registerButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:

        String username = usernameForm.getText();
        String password = passwordForm.getText();

        LoginRequest request = new LoginRequest(username, password);

        String errorMessage = authService.loginStaff(request);

        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage, "Validasi Gagal", JOptionPane.ERROR_MESSAGE);
        } else {
            clearField();
            JOptionPane.showMessageDialog(this, "Berhasil login");
            dashboard.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    public void clearField(){
        
        usernameForm.setText("");
        passwordForm.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordForm;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameForm;
    // End of variables declaration//GEN-END:variables
}
